# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: build
      run: |
        npm install
        npm run build
        npm run deploy
      env:
        REACT_APP_API_URL: ${{secrets.REACT_APP_API_URL}} 
      
    - name: deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with: 
        BRANCH: gh-pages
        FOLDER: build
